services:
  - type: web
    name: car-finder
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: PERPLEXITY_API_KEY
        sync: false  # You'll set this in Render dashboard
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1 